### PR TITLE
Add Discord Link and fix speech marks in translations.

### LINKED ISSUE #46: Add Discord link to top nav
From https://github.com/simple-icons/simple-icons-website/pull/301

### LINKED ISSUE #47: English string includes speechmarks!
See https://github.com/mondeja/simple-icons-website-rs/blob/c0d762dd48622dd3dab990347123b81a2cc14e1a/i18n/locales/en-US/main.ftl#L24 - the English 'translation' of this page includes speech marks. I'm assuming a carry-over from the old translation file!

### PR DESCRIPTION
**Pull request by adamrusted**
Closes #46
Closes #47

### CODE REVIEW

**Comment by mondeja** [comment]
Ah, OK!! 😆

**Comment by adamrusted** [comment]
Ah, it would appear the speech marks are in _all_ translations. Bear with while I remove them - they look a bit weird displayed on the site...
image

**Comment by adamrusted** [comment]
@mondeja - this should be good to go now!

**Review by mondeja — APPROVED** [review]
Great, thank you @adamrusted! 🥇

**Pull request merged**
